<?php

namespace Pracapl\ZnajdzPraceZPracapl\View;

class Country
{
    public static function items(): array
    {
        return [
            163 => __('Poland', 'znajdz-prace-z-pracapl'),
            1 => __('Afghanistan', 'znajdz-prace-z-pracapl'),
            2 => __('Albania', 'znajdz-prace-z-pracapl'),
            3 => __('Algeria', 'znajdz-prace-z-pracapl'),
            4 => __('Saudi Arabia', 'znajdz-prace-z-pracapl'),
            5 => __('Argentina', 'znajdz-prace-z-pracapl'),
            6 => __('Australia', 'znajdz-prace-z-pracapl'),
            7 => __('Austria', 'znajdz-prace-z-pracapl'),
            8 => __('Belgium', 'znajdz-prace-z-pracapl'),
            9 => __('Belarus', 'znajdz-prace-z-pracapl'),
            10 => __('Bosnia and Herzegovina', 'znajdz-prace-z-pracapl'),
            11 => __('Brazil', 'znajdz-prace-z-pracapl'),
            12 => __('Bulgaria', 'znajdz-prace-z-pracapl'),
            13 => __('Chile', 'znajdz-prace-z-pracapl'),
            14 => __('China', 'znajdz-prace-z-pracapl'),
            15 => __('Croatia', 'znajdz-prace-z-pracapl'),
            16 => __('Czech', 'znajdz-prace-z-pracapl'),
            17 => __('Denmark', 'znajdz-prace-z-pracapl'),
            18 => __('Egypt', 'znajdz-prace-z-pracapl'),
            19 => __('Ecuador', 'znajdz-prace-z-pracapl'),
            20 => __('Estonia', 'znajdz-prace-z-pracapl'),
            21 => __('Philippines', 'znajdz-prace-z-pracapl'),
            22 => __('Finland', 'znajdz-prace-z-pracapl'),
            23 => __('France', 'znajdz-prace-z-pracapl'),
            24 => __('Greece', 'znajdz-prace-z-pracapl'),
            25 => __('Spain', 'znajdz-prace-z-pracapl'),
            26 => __('Netherlands', 'znajdz-prace-z-pracapl'),
            27 => __('India', 'znajdz-prace-z-pracapl'),
            28 => __('Indonesia', 'znajdz-prace-z-pracapl'),
            29 => __('Ireland', 'znajdz-prace-z-pracapl'),
            30 => __('Israel', 'znajdz-prace-z-pracapl'),
            31 => __('Japan', 'znajdz-prace-z-pracapl'),
            32 => __('Jordan', 'znajdz-prace-z-pracapl'),
            34 => __('Canada', 'znajdz-prace-z-pracapl'),
            35 => __('Colombia', 'znajdz-prace-z-pracapl'),
            36 => __('South Korea', 'znajdz-prace-z-pracapl'),
            37 => __('Costa Rica', 'znajdz-prace-z-pracapl'),
            38 => __('Lebanon', 'znajdz-prace-z-pracapl'),
            39 => __('Lithuania', 'znajdz-prace-z-pracapl'),
            40 => __('Latvia', 'znajdz-prace-z-pracapl'),
            41 => __('Malaysia', 'znajdz-prace-z-pracapl'),
            42 => __('Morocco', 'znajdz-prace-z-pracapl'),
            43 => __('Mexico', 'znajdz-prace-z-pracapl'),
            44 => __('Germany', 'znajdz-prace-z-pracapl'),
            45 => __('Norway', 'znajdz-prace-z-pracapl'),
            46 => __('New Zealand', 'znajdz-prace-z-pracapl'),
            47 => __('Pakistan', 'znajdz-prace-z-pracapl'),
            48 => __('Peru', 'znajdz-prace-z-pracapl'),
            50 => __('Portugal', 'znajdz-prace-z-pracapl'),
            51 => __('South Africa', 'znajdz-prace-z-pracapl'),
            52 => __('Russia', 'znajdz-prace-z-pracapl'),
            53 => __('Romania', 'znajdz-prace-z-pracapl'),
            54 => __('El Salvador', 'znajdz-prace-z-pracapl'),
            55 => __('Singapore', 'znajdz-prace-z-pracapl'),
            56 => __('Slovakia', 'znajdz-prace-z-pracapl'),
            57 => __('Slovenia', 'znajdz-prace-z-pracapl'),
            58 => __('United States', 'znajdz-prace-z-pracapl'),
            59 => __('Switzerland', 'znajdz-prace-z-pracapl'),
            60 => __('Sweden', 'znajdz-prace-z-pracapl'),
            61 => __('Thailand', 'znajdz-prace-z-pracapl'),
            62 => __('Taiwan', 'znajdz-prace-z-pracapl'),
            63 => __('Tunisia', 'znajdz-prace-z-pracapl'),
            64 => __('Turkey', 'znajdz-prace-z-pracapl'),
            65 => __('Ukraine', 'znajdz-prace-z-pracapl'),
            66 => __('Venezuela', 'znajdz-prace-z-pracapl'),
            67 => __('Hungary', 'znajdz-prace-z-pracapl'),
            68 => __('United Kingdom', 'znajdz-prace-z-pracapl'),
            69 => __('Italy', 'znajdz-prace-z-pracapl'),
            70 => __('United Arab Emirates', 'znajdz-prace-z-pracapl'),
            71 => __('Other/World', 'znajdz-prace-z-pracapl'),
            72 => __('Cyprus', 'znajdz-prace-z-pracapl'),
            73 => __('Iceland', 'znajdz-prace-z-pracapl'),
            74 => __('Luxembourg', 'znajdz-prace-z-pracapl'),
            75 => __('Kuwait', 'znajdz-prace-z-pracapl'),
            76 => __('Serbia', 'znajdz-prace-z-pracapl'),
            77 => __('Moldova', 'znajdz-prace-z-pracapl'),
            78 => __('Andorra', 'znajdz-prace-z-pracapl'),
            164 => __('Liechtenstein', 'znajdz-prace-z-pracapl')
        ];
    }
}